package com.example.demo.model;

public class Feedback {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.f_id
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    private Long fId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.u_id
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    private Long uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.content
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.is_delete
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    private Boolean isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.f_id
     *
     * @return the value of feedback.f_id
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    public Long getfId() {
        return fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.f_id
     *
     * @param fId the value for feedback.f_id
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    public void setfId(Long fId) {
        this.fId = fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.u_id
     *
     * @return the value of feedback.u_id
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    public Long getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.u_id
     *
     * @param uId the value for feedback.u_id
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    public void setuId(Long uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.content
     *
     * @return the value of feedback.content
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.content
     *
     * @param content the value for feedback.content
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.is_delete
     *
     * @return the value of feedback.is_delete
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.is_delete
     *
     * @param isDelete the value for feedback.is_delete
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }
}