package com.example.demo.model;

public class ScoreType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_type.st_id
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    private Long stId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_type.at_id
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    private Long atId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_type.s_value
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    private Float sValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_type.st_id
     *
     * @return the value of score_type.st_id
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    public Long getStId() {
        return stId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_type.st_id
     *
     * @param stId the value for score_type.st_id
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    public void setStId(Long stId) {
        this.stId = stId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_type.at_id
     *
     * @return the value of score_type.at_id
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    public Long getAtId() {
        return atId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_type.at_id
     *
     * @param atId the value for score_type.at_id
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    public void setAtId(Long atId) {
        this.atId = atId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_type.s_value
     *
     * @return the value of score_type.s_value
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    public Float getsValue() {
        return sValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_type.s_value
     *
     * @param sValue the value for score_type.s_value
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    public void setsValue(Float sValue) {
        this.sValue = sValue;
    }
}