package com.example.demo.model;

import java.util.Date;

public class UserActivity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_activity.ua_id
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    private Long uaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_activity.a_id
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    private Long aId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_activity.time
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_activity.ua_id
     *
     * @return the value of user_activity.ua_id
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    public Long getUaId() {
        return uaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_activity.ua_id
     *
     * @param uaId the value for user_activity.ua_id
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    public void setUaId(Long uaId) {
        this.uaId = uaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_activity.a_id
     *
     * @return the value of user_activity.a_id
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    public Long getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_activity.a_id
     *
     * @param aId the value for user_activity.a_id
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    public void setaId(Long aId) {
        this.aId = aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_activity.time
     *
     * @return the value of user_activity.time
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_activity.time
     *
     * @param time the value for user_activity.time
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    public void setTime(Date time) {
        this.time = time;
    }
}