package com.example.demo.model;

public class ActivityType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_type.at_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Long atId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_type.at_module
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private String atModule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_type.at_name
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private String atName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_type.at_id
     *
     * @return the value of activity_type.at_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Long getAtId() {
        return atId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_type.at_id
     *
     * @param atId the value for activity_type.at_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setAtId(Long atId) {
        this.atId = atId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_type.at_module
     *
     * @return the value of activity_type.at_module
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public String getAtModule() {
        return atModule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_type.at_module
     *
     * @param atModule the value for activity_type.at_module
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setAtModule(String atModule) {
        this.atModule = atModule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_type.at_name
     *
     * @return the value of activity_type.at_name
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public String getAtName() {
        return atName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_type.at_name
     *
     * @param atName the value for activity_type.at_name
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setAtName(String atName) {
        this.atName = atName;
    }
}