package com.example.demo.model;

import java.util.Date;

public class Activity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.a_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Long aId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.a_name
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private String aName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.at_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Long atId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.level
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.start_time
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.end_time
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.award_content
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private String awardContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.c_point
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Float cPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.content
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.a_id
     *
     * @return the value of activity.a_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Long getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.a_id
     *
     * @param aId the value for activity.a_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setaId(Long aId) {
        this.aId = aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.a_name
     *
     * @return the value of activity.a_name
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public String getaName() {
        return aName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.a_name
     *
     * @param aName the value for activity.a_name
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setaName(String aName) {
        this.aName = aName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.at_id
     *
     * @return the value of activity.at_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Long getAtId() {
        return atId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.at_id
     *
     * @param atId the value for activity.at_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setAtId(Long atId) {
        this.atId = atId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.level
     *
     * @return the value of activity.level
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.level
     *
     * @param level the value for activity.level
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.start_time
     *
     * @return the value of activity.start_time
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.start_time
     *
     * @param startTime the value for activity.start_time
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.end_time
     *
     * @return the value of activity.end_time
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.end_time
     *
     * @param endTime the value for activity.end_time
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.award_content
     *
     * @return the value of activity.award_content
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public String getAwardContent() {
        return awardContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.award_content
     *
     * @param awardContent the value for activity.award_content
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setAwardContent(String awardContent) {
        this.awardContent = awardContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.c_point
     *
     * @return the value of activity.c_point
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Float getcPoint() {
        return cPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.c_point
     *
     * @param cPoint the value for activity.c_point
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setcPoint(Float cPoint) {
        this.cPoint = cPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.content
     *
     * @return the value of activity.content
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.content
     *
     * @param content the value for activity.content
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setContent(String content) {
        this.content = content;
    }
}