package com.example.demo.model;

import java.util.ArrayList;
import java.util.List;

public class ActivityTypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity_type
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity_type
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity_type
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_type
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public ActivityTypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_type
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_type
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_type
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_type
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_type
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_type
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_type
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_type
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_type
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_type
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table activity_type
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAtIdIsNull() {
            addCriterion("at_id is null");
            return (Criteria) this;
        }

        public Criteria andAtIdIsNotNull() {
            addCriterion("at_id is not null");
            return (Criteria) this;
        }

        public Criteria andAtIdEqualTo(Long value) {
            addCriterion("at_id =", value, "atId");
            return (Criteria) this;
        }

        public Criteria andAtIdNotEqualTo(Long value) {
            addCriterion("at_id <>", value, "atId");
            return (Criteria) this;
        }

        public Criteria andAtIdGreaterThan(Long value) {
            addCriterion("at_id >", value, "atId");
            return (Criteria) this;
        }

        public Criteria andAtIdGreaterThanOrEqualTo(Long value) {
            addCriterion("at_id >=", value, "atId");
            return (Criteria) this;
        }

        public Criteria andAtIdLessThan(Long value) {
            addCriterion("at_id <", value, "atId");
            return (Criteria) this;
        }

        public Criteria andAtIdLessThanOrEqualTo(Long value) {
            addCriterion("at_id <=", value, "atId");
            return (Criteria) this;
        }

        public Criteria andAtIdIn(List<Long> values) {
            addCriterion("at_id in", values, "atId");
            return (Criteria) this;
        }

        public Criteria andAtIdNotIn(List<Long> values) {
            addCriterion("at_id not in", values, "atId");
            return (Criteria) this;
        }

        public Criteria andAtIdBetween(Long value1, Long value2) {
            addCriterion("at_id between", value1, value2, "atId");
            return (Criteria) this;
        }

        public Criteria andAtIdNotBetween(Long value1, Long value2) {
            addCriterion("at_id not between", value1, value2, "atId");
            return (Criteria) this;
        }

        public Criteria andAtModuleIsNull() {
            addCriterion("at_module is null");
            return (Criteria) this;
        }

        public Criteria andAtModuleIsNotNull() {
            addCriterion("at_module is not null");
            return (Criteria) this;
        }

        public Criteria andAtModuleEqualTo(String value) {
            addCriterion("at_module =", value, "atModule");
            return (Criteria) this;
        }

        public Criteria andAtModuleNotEqualTo(String value) {
            addCriterion("at_module <>", value, "atModule");
            return (Criteria) this;
        }

        public Criteria andAtModuleGreaterThan(String value) {
            addCriterion("at_module >", value, "atModule");
            return (Criteria) this;
        }

        public Criteria andAtModuleGreaterThanOrEqualTo(String value) {
            addCriterion("at_module >=", value, "atModule");
            return (Criteria) this;
        }

        public Criteria andAtModuleLessThan(String value) {
            addCriterion("at_module <", value, "atModule");
            return (Criteria) this;
        }

        public Criteria andAtModuleLessThanOrEqualTo(String value) {
            addCriterion("at_module <=", value, "atModule");
            return (Criteria) this;
        }

        public Criteria andAtModuleLike(String value) {
            addCriterion("at_module like", value, "atModule");
            return (Criteria) this;
        }

        public Criteria andAtModuleNotLike(String value) {
            addCriterion("at_module not like", value, "atModule");
            return (Criteria) this;
        }

        public Criteria andAtModuleIn(List<String> values) {
            addCriterion("at_module in", values, "atModule");
            return (Criteria) this;
        }

        public Criteria andAtModuleNotIn(List<String> values) {
            addCriterion("at_module not in", values, "atModule");
            return (Criteria) this;
        }

        public Criteria andAtModuleBetween(String value1, String value2) {
            addCriterion("at_module between", value1, value2, "atModule");
            return (Criteria) this;
        }

        public Criteria andAtModuleNotBetween(String value1, String value2) {
            addCriterion("at_module not between", value1, value2, "atModule");
            return (Criteria) this;
        }

        public Criteria andAtNameIsNull() {
            addCriterion("at_name is null");
            return (Criteria) this;
        }

        public Criteria andAtNameIsNotNull() {
            addCriterion("at_name is not null");
            return (Criteria) this;
        }

        public Criteria andAtNameEqualTo(String value) {
            addCriterion("at_name =", value, "atName");
            return (Criteria) this;
        }

        public Criteria andAtNameNotEqualTo(String value) {
            addCriterion("at_name <>", value, "atName");
            return (Criteria) this;
        }

        public Criteria andAtNameGreaterThan(String value) {
            addCriterion("at_name >", value, "atName");
            return (Criteria) this;
        }

        public Criteria andAtNameGreaterThanOrEqualTo(String value) {
            addCriterion("at_name >=", value, "atName");
            return (Criteria) this;
        }

        public Criteria andAtNameLessThan(String value) {
            addCriterion("at_name <", value, "atName");
            return (Criteria) this;
        }

        public Criteria andAtNameLessThanOrEqualTo(String value) {
            addCriterion("at_name <=", value, "atName");
            return (Criteria) this;
        }

        public Criteria andAtNameLike(String value) {
            addCriterion("at_name like", value, "atName");
            return (Criteria) this;
        }

        public Criteria andAtNameNotLike(String value) {
            addCriterion("at_name not like", value, "atName");
            return (Criteria) this;
        }

        public Criteria andAtNameIn(List<String> values) {
            addCriterion("at_name in", values, "atName");
            return (Criteria) this;
        }

        public Criteria andAtNameNotIn(List<String> values) {
            addCriterion("at_name not in", values, "atName");
            return (Criteria) this;
        }

        public Criteria andAtNameBetween(String value1, String value2) {
            addCriterion("at_name between", value1, value2, "atName");
            return (Criteria) this;
        }

        public Criteria andAtNameNotBetween(String value1, String value2) {
            addCriterion("at_name not between", value1, value2, "atName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table activity_type
     *
     * @mbg.generated do_not_delete_during_merge Fri Sep 13 14:56:58 CST 2024
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table activity_type
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}