package com.example.demo.model;

public class Additional {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column additional.ad_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Long adId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column additional.file
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private String file;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column additional.is_delete
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Boolean isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column additional.ad_id
     *
     * @return the value of additional.ad_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Long getAdId() {
        return adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column additional.ad_id
     *
     * @param adId the value for additional.ad_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setAdId(Long adId) {
        this.adId = adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column additional.file
     *
     * @return the value of additional.file
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public String getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column additional.file
     *
     * @param file the value for additional.file
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setFile(String file) {
        this.file = file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column additional.is_delete
     *
     * @return the value of additional.is_delete
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column additional.is_delete
     *
     * @param isDelete the value for additional.is_delete
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }
}