package com.example.demo.model;

public class Administrator {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.p_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Integer pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.username
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.password
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.phone
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.email
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.is_delete
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Boolean isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.id
     *
     * @return the value of administrator.id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.id
     *
     * @param id the value for administrator.id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.p_id
     *
     * @return the value of administrator.p_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.p_id
     *
     * @param pId the value for administrator.p_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.username
     *
     * @return the value of administrator.username
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.username
     *
     * @param username the value for administrator.username
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.password
     *
     * @return the value of administrator.password
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.password
     *
     * @param password the value for administrator.password
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.phone
     *
     * @return the value of administrator.phone
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.phone
     *
     * @param phone the value for administrator.phone
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.email
     *
     * @return the value of administrator.email
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.email
     *
     * @param email the value for administrator.email
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.is_delete
     *
     * @return the value of administrator.is_delete
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.is_delete
     *
     * @param isDelete the value for administrator.is_delete
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }
}