package com.example.demo.model;

public class Apply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.ap_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Long apId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.photo
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.is_delete
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Boolean isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.ap_id
     *
     * @return the value of apply.ap_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Long getApId() {
        return apId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.ap_id
     *
     * @param apId the value for apply.ap_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setApId(Long apId) {
        this.apId = apId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.photo
     *
     * @return the value of apply.photo
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.photo
     *
     * @param photo the value for apply.photo
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.is_delete
     *
     * @return the value of apply.is_delete
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.is_delete
     *
     * @param isDelete the value for apply.is_delete
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }
}