package com.example.demo.model;

public class Credit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit.c_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Long cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit.at_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Long atId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit.politics
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Integer politics;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit.practice
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Integer practice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit.society
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Integer society;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit.innovate
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Integer innovate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit.sports
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Integer sports;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit.work
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Integer work;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit.skill
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Integer skill;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit.other
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Integer other;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit.is_delete
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Boolean isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit.c_id
     *
     * @return the value of credit.c_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Long getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit.c_id
     *
     * @param cId the value for credit.c_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setcId(Long cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit.at_id
     *
     * @return the value of credit.at_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Long getAtId() {
        return atId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit.at_id
     *
     * @param atId the value for credit.at_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setAtId(Long atId) {
        this.atId = atId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit.politics
     *
     * @return the value of credit.politics
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Integer getPolitics() {
        return politics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit.politics
     *
     * @param politics the value for credit.politics
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setPolitics(Integer politics) {
        this.politics = politics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit.practice
     *
     * @return the value of credit.practice
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Integer getPractice() {
        return practice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit.practice
     *
     * @param practice the value for credit.practice
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setPractice(Integer practice) {
        this.practice = practice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit.society
     *
     * @return the value of credit.society
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Integer getSociety() {
        return society;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit.society
     *
     * @param society the value for credit.society
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setSociety(Integer society) {
        this.society = society;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit.innovate
     *
     * @return the value of credit.innovate
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Integer getInnovate() {
        return innovate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit.innovate
     *
     * @param innovate the value for credit.innovate
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setInnovate(Integer innovate) {
        this.innovate = innovate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit.sports
     *
     * @return the value of credit.sports
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Integer getSports() {
        return sports;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit.sports
     *
     * @param sports the value for credit.sports
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setSports(Integer sports) {
        this.sports = sports;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit.work
     *
     * @return the value of credit.work
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Integer getWork() {
        return work;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit.work
     *
     * @param work the value for credit.work
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setWork(Integer work) {
        this.work = work;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit.skill
     *
     * @return the value of credit.skill
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Integer getSkill() {
        return skill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit.skill
     *
     * @param skill the value for credit.skill
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setSkill(Integer skill) {
        this.skill = skill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit.other
     *
     * @return the value of credit.other
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Integer getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit.other
     *
     * @param other the value for credit.other
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setOther(Integer other) {
        this.other = other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit.is_delete
     *
     * @return the value of credit.is_delete
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit.is_delete
     *
     * @param isDelete the value for credit.is_delete
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }
}