package com.example.demo.model;

public class Permission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.p_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Integer pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.authority
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Integer authority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.describes
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private String describes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.p_id
     *
     * @return the value of permission.p_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.p_id
     *
     * @param pId the value for permission.p_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.authority
     *
     * @return the value of permission.authority
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Integer getAuthority() {
        return authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.authority
     *
     * @param authority the value for permission.authority
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setAuthority(Integer authority) {
        this.authority = authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.describes
     *
     * @return the value of permission.describes
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public String getDescribes() {
        return describes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.describes
     *
     * @param describes the value for permission.describes
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setDescribes(String describes) {
        this.describes = describes;
    }
}