package com.example.demo.model;

public class Score {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.s_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Long sId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.at_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Long atId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.politics
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Float politics;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.practice
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Float practice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.society
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Float society;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.innovate
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Float innovate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.sports
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Float sports;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.work
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Float work;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.skill
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Float skill;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.other
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Float other;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.is_delete
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Boolean isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.s_id
     *
     * @return the value of score.s_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Long getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.s_id
     *
     * @param sId the value for score.s_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setsId(Long sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.at_id
     *
     * @return the value of score.at_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Long getAtId() {
        return atId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.at_id
     *
     * @param atId the value for score.at_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setAtId(Long atId) {
        this.atId = atId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.politics
     *
     * @return the value of score.politics
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Float getPolitics() {
        return politics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.politics
     *
     * @param politics the value for score.politics
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setPolitics(Float politics) {
        this.politics = politics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.practice
     *
     * @return the value of score.practice
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Float getPractice() {
        return practice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.practice
     *
     * @param practice the value for score.practice
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setPractice(Float practice) {
        this.practice = practice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.society
     *
     * @return the value of score.society
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Float getSociety() {
        return society;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.society
     *
     * @param society the value for score.society
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setSociety(Float society) {
        this.society = society;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.innovate
     *
     * @return the value of score.innovate
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Float getInnovate() {
        return innovate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.innovate
     *
     * @param innovate the value for score.innovate
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setInnovate(Float innovate) {
        this.innovate = innovate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.sports
     *
     * @return the value of score.sports
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Float getSports() {
        return sports;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.sports
     *
     * @param sports the value for score.sports
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setSports(Float sports) {
        this.sports = sports;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.work
     *
     * @return the value of score.work
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Float getWork() {
        return work;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.work
     *
     * @param work the value for score.work
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setWork(Float work) {
        this.work = work;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.skill
     *
     * @return the value of score.skill
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Float getSkill() {
        return skill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.skill
     *
     * @param skill the value for score.skill
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setSkill(Float skill) {
        this.skill = skill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.other
     *
     * @return the value of score.other
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Float getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.other
     *
     * @param other the value for score.other
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setOther(Float other) {
        this.other = other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.is_delete
     *
     * @return the value of score.is_delete
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.is_delete
     *
     * @param isDelete the value for score.is_delete
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }
}