package com.example.demo.model;

public class UserApply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_apply.uap_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Long uapId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_apply.u_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Long uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_apply.ap_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Long apId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_apply.is_delete
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    private Boolean isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_apply.uap_id
     *
     * @return the value of user_apply.uap_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Long getUapId() {
        return uapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_apply.uap_id
     *
     * @param uapId the value for user_apply.uap_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setUapId(Long uapId) {
        this.uapId = uapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_apply.u_id
     *
     * @return the value of user_apply.u_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Long getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_apply.u_id
     *
     * @param uId the value for user_apply.u_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setuId(Long uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_apply.ap_id
     *
     * @return the value of user_apply.ap_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Long getApId() {
        return apId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_apply.ap_id
     *
     * @param apId the value for user_apply.ap_id
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setApId(Long apId) {
        this.apId = apId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_apply.is_delete
     *
     * @return the value of user_apply.is_delete
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_apply.is_delete
     *
     * @param isDelete the value for user_apply.is_delete
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }
}