package com.example.demo.Mapper;

import com.example.demo.model.ActivityType;
import com.example.demo.model.ActivityTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActivityTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_type
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    long countByExample(ActivityTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_type
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int deleteByExample(ActivityTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_type
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int deleteByPrimaryKey(Long atId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_type
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int insert(ActivityType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_type
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int insertSelective(ActivityType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_type
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    List<ActivityType> selectByExample(ActivityTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_type
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    ActivityType selectByPrimaryKey(Long atId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_type
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int updateByExampleSelective(@Param("record") ActivityType record, @Param("example") ActivityTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_type
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int updateByExample(@Param("record") ActivityType record, @Param("example") ActivityTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_type
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int updateByPrimaryKeySelective(ActivityType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_type
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int updateByPrimaryKey(ActivityType record);
}