package com.example.demo.Mapper;

import com.example.demo.model.Additional;
import com.example.demo.model.AdditionalExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdditionalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table additional
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    long countByExample(AdditionalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table additional
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int deleteByExample(AdditionalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table additional
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int deleteByPrimaryKey(Long adId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table additional
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int insert(Additional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table additional
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int insertSelective(Additional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table additional
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    List<Additional> selectByExample(AdditionalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table additional
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    Additional selectByPrimaryKey(Long adId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table additional
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int updateByExampleSelective(@Param("record") Additional record, @Param("example") AdditionalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table additional
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int updateByExample(@Param("record") Additional record, @Param("example") AdditionalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table additional
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int updateByPrimaryKeySelective(Additional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table additional
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int updateByPrimaryKey(Additional record);
}