package com.example.demo.Mapper;

import com.example.demo.model.Credit;
import com.example.demo.model.CreditExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CreditMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    long countByExample(CreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int deleteByExample(CreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int deleteByPrimaryKey(Long cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int insert(Credit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int insertSelective(Credit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    List<Credit> selectByExample(CreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    Credit selectByPrimaryKey(Long cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int updateByExampleSelective(@Param("record") Credit record, @Param("example") CreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int updateByExample(@Param("record") Credit record, @Param("example") CreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int updateByPrimaryKeySelective(Credit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int updateByPrimaryKey(Credit record);
}