package com.example.demo.Mapper;

import com.example.demo.model.ScoreType;
import com.example.demo.model.ScoreTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScoreTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_type
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    long countByExample(ScoreTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_type
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int deleteByExample(ScoreTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_type
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int deleteByPrimaryKey(Long stId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_type
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int insert(ScoreType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_type
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int insertSelective(ScoreType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_type
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    List<ScoreType> selectByExample(ScoreTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_type
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    ScoreType selectByPrimaryKey(Long stId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_type
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int updateByExampleSelective(@Param("record") ScoreType record, @Param("example") ScoreTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_type
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int updateByExample(@Param("record") ScoreType record, @Param("example") ScoreTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_type
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int updateByPrimaryKeySelective(ScoreType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_type
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int updateByPrimaryKey(ScoreType record);
}