package com.example.demo.Mapper;

import com.example.demo.model.UserActivity;
import com.example.demo.model.UserActivityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_activity
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    long countByExample(UserActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_activity
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int deleteByExample(UserActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_activity
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int deleteByPrimaryKey(Long uaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_activity
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int insert(UserActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_activity
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int insertSelective(UserActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_activity
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    List<UserActivity> selectByExample(UserActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_activity
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    UserActivity selectByPrimaryKey(Long uaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_activity
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int updateByExampleSelective(@Param("record") UserActivity record, @Param("example") UserActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_activity
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int updateByExample(@Param("record") UserActivity record, @Param("example") UserActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_activity
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int updateByPrimaryKeySelective(UserActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_activity
     *
     * @mbg.generated Thu Sep 12 16:59:01 CST 2024
     */
    int updateByPrimaryKey(UserActivity record);
}