package com.example.demo.Mapper;

import com.example.demo.model.Materials;
import com.example.demo.model.MaterialsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MaterialsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materials
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    long countByExample(MaterialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materials
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    int deleteByExample(MaterialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materials
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    int deleteByPrimaryKey(Long mId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materials
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    int insert(Materials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materials
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    int insertSelective(Materials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materials
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    List<Materials> selectByExample(MaterialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materials
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    Materials selectByPrimaryKey(Long mId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materials
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    int updateByExampleSelective(@Param("record") Materials record, @Param("example") MaterialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materials
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    int updateByExample(@Param("record") Materials record, @Param("example") MaterialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materials
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    int updateByPrimaryKeySelective(Materials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materials
     *
     * @mbg.generated Fri Sep 13 14:56:58 CST 2024
     */
    int updateByPrimaryKey(Materials record);
}